version: "3"

services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.pyspark
    image: jupyter/pyspark-notebook
    container_name: practice-pyspark
    ports:
      - "8890:8888"
    volumes:
      - ./docker/work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''